services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: addinputv2-container
    ports:
      - '3000:3000'
    volumes:
      - ./:/addinputv2\
    command: pnpm dev -o